In [2]:
import numpy as np
import torch

In [10]:
a = torch.arange(6).reshape(2, 3)
torch.einsum('ij->ji', a)

tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [11]:
np.einsum('ij->ji', np.array(a))

array([[0, 3],
       [1, 4],
       [2, 5]])

In [15]:
torch.einsum('ij->', a)

tensor(15)

In [18]:
a = torch.arange(6).reshape(2, 3)
b = torch.arange(3)
torch.einsum('xk,k->x', [a, b])

tensor([ 5, 14])

In [22]:
a = torch.arange(6).reshape(2, 3)
b = torch.arange(9).reshape(3, 3)
torch.einsum('ik,kj->ij', [a, b])

tensor([[15, 18, 21],
        [42, 54, 66]])

In [23]:
a = torch.arange(3)
b = torch.arange(3,6)  # [3, 4, 5]
torch.einsum('i,i->', [a, b])

tensor(14)

In [24]:
a = torch.arange(6).reshape(2, 3)
b = torch.arange(6,12).reshape(2, 3)
torch.einsum('ij,ij->', [a, b])

tensor(145)

In [25]:
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [51]:
import tensorflow as tf
import numpy as np
import torch

In [52]:
v = np.arange(100)
M = np.arange(16).reshape(4,4)
A = np.arange(25).reshape(5,5)
B = np.arange(20).reshape(5,4)
s = np.einsum('a->', v)
T = np.einsum('ij->ji', M)
C = np.einsum('mn,np->mp', A,B)

assert v.ndim == len('a')
assert s.ndim == len('')
assert M.ndim == len('ij')
assert T.ndim == len('ji')
assert A.ndim == len('mn')
assert B.ndim == len('np')
assert C.ndim == len('mp')

In [57]:
a = torch.arange(25).reshape(5,5)
torch.einsum('ii->i', a)

tensor([ 0,  6, 12, 18, 24])

In [58]:
# 15: MLP Backprop done easily (stochastic version).
#     h = sigmoid(Wx + b)
#     y = softmax(Vh + c)
Ni = 784
Nh = 500
No =  10
 
W  = np.random.normal(size = (Nh,Ni))  # Nh x Ni
b  = np.random.normal(size = (Nh,))    # Nh
V  = np.random.normal(size = (No,Nh))  # No x Nh
c  = np.random.normal(size = (No,))    # No
 
# Load x and t...
x, t  = train_set[k]
 
# With a judicious, consistent choice of index labels, we can
# express fprop() and bprop() extremely tersely; No thought
# needs to be given about the details of shoehorning matrices
# into np.dot(), such as the exact argument order and the
# required transpositions.
#
# Let
#
#     'i' be the input  dimension label.
#     'h' be the hidden dimension label.
#     'o' be the output dimension label.
#
# Then
 
# Fprop
ha    = np.einsum("hi, i -> h", W, x) + b
h     = sigmoid(ha)
ya    = np.einsum("oh, h -> o", V, h) + c
y     = softmax(ya)
 
# Bprop
dLdya = y - t
dLdV  = np.einsum("h , o -> oh", h, dLdya)
dLdc  = dLdya
dLdh  = np.einsum("oh, o -> h ", V, dLdya)
dLdha = dLdh * sigmoidgrad(ha)
dLdW  = np.einsum("i,  h -> hi", x, dLdha)
dLdb  = dLdha

NameError: name 'train_set' is not defined

In [59]:
import torch
a = torch.arange(24).reshape(4, 6)
torch.einsum('ij->ji', [a])

tensor([[ 0,  6, 12, 18],
        [ 1,  7, 13, 19],
        [ 2,  8, 14, 20],
        [ 3,  9, 15, 21],
        [ 4, 10, 16, 22],
        [ 5, 11, 17, 23]])

In [61]:
a = torch.arange(6).reshape(2, 3)
torch.einsum('ij->', [a])

tensor(15)

In [62]:
a = torch.arange(6).reshape(2, 3)
torch.einsum('ij->j', [a])

tensor([3, 5, 7])

In [63]:
a = torch.arange(6).reshape(2, 3)
b = torch.arange(3)
torch.einsum('ik,k->i', [a, b])

tensor([ 5, 14])

In [64]:
a = torch.arange(6).reshape(2, 3)
b = torch.arange(15).reshape(3, 5)
torch.einsum('ik,kj->ij', [a, b])


tensor([[ 25,  28,  31,  34,  37],
        [ 70,  82,  94, 106, 118]])

In [67]:
a = torch.arange(9).reshape(3, 3)
torch.einsum('ii->', a)

tensor(12)

In [68]:
a = torch.arange(3)
b = torch.arange(3,6)  # [3, 4, 5]
torch.einsum('i,i->', [a, b])

tensor(14)

In [69]:
a = torch.arange(6).reshape(2, 3)
b = torch.arange(6,12).reshape(2, 3)
torch.einsum('ij,ij->ij', [a, b])

tensor([[ 0,  7, 16],
        [27, 40, 55]])

In [70]:
a,b

(tensor([[0, 1, 2],
         [3, 4, 5]]), tensor([[ 6,  7,  8],
         [ 9, 10, 11]]))

In [71]:
a = torch.randn(3,2,5)
b = torch.randn(3,5,3)
torch.einsum('ijk,ikl->ijl', [a, b])

tensor([[[-0.1173,  3.7414,  1.3514],
         [-0.6257, -4.3871, -2.1713]],

        [[ 1.5745, -1.0539, -1.4146],
         [-0.9819,  1.7112, -0.3158]],

        [[ 0.4060, -1.2728,  0.3768],
         [ 1.5115,  2.1749,  0.3906]]])